version: '3'

volumes:
  pgdata:
  
services:
    db:
        image: 'postgres:15'
        env_file:
            - .env
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5430:5432'
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - CARGO_TARGET_DIR=/target
        volumes:
            - '.:/usr/src/app'
        depends_on:
            - db
        ports:
            - '8080:8080'
        command: 'bash -c "cargo watch -x run"'