version: '3'
services:
    db:
        image: 'postgres:15-alpine'
        env_file:
          - ../.env
        ports:
            - '5430:5432'
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
          - ../.env
        volumes:
            - './../:/usr/src/app'
        depends_on:
            - db
        command: 'bash -c "cargo watch -x run"'
        ports:
            - '8080:8080'